Add Reset method to be able to re-use the Pinger instance
go-ping/ping pull request #117
Opened 2020-10-26 10:53 UTC by zekroTJA

I have a specific use case where I want to periodically determine the RTT to a server. 

I tried to re-use the `Pinger` instance and used `Run` on every ticker elapse on the same instance. The result was that every following `Statistics` instance contained the same RTT times. Below, you can find the snippet for this.
https://gist.github.com/zekroTJA/ae3dbbe2dbbe56b3c1be9775f77718f5

To be able to re-use the `Pinger` instance, I have added a `Reset` method which reinitializes the `done` channel and the `rtts` array and sets the values of `PacketsSent` and `PacketsRecv` back to zero.

2020-10-26 11:35 UTC, SuperQ commented
If you want to track the RTT to a server, maybe it's easier to make your own hook into OnRecv. This is what I do in the [smokeping_prober](https://github.com/SuperQ/smokeping_prober/blob/9ba85274dcc21bf8132cbe3b3dccfcb4aab57d9f/collector.go#L66-L71).

2021-02-04 21:38 UTC, CHTJonas commented
@zekroTJA could you rebase this on top of the latest `master` please?

While I'm not sure the code in your gist is necessarily the best way to go about achieving want I think you're trying to, I can see the use of a `Reset()` method in other situations; it could be very useful for people who want to reuse a pinger instance many times in order to avoid GC churn.

2021-02-04 21:39 UTC, CHTJonas requested changes
@zekroTJA could you rebase this on top of the latest `master` please?

While I'm not sure the code in your gist is necessarily the best way to go about achieving want I think you're trying to, I can see the use of a `Reset()` method in other situations; it could be very useful for people who want to reuse a pinger instance many times in order to avoid GC churn.

2021-09-11 15:30 UTC, CHTJonas commented
@zekroTJA, please rebase!

2023-01-21 22:39 UTC, SuperQ commented
See https://github.com/go-ping/ping/pull/226

2023-01-21 22:39 UTC, closed without merging