Bugfix: handle when NewPinger with empty ip addr.
go-ping/ping pull request #89
Opened 2020-07-21 07:01 UTC by hustclf

When NewPinger with empty ip addr,  ping.Run will hangs forever.

for example
```
func main()  {
	pinger, err := NewPinger("")
	pinger.Run()
}
```

this pr check if addr is empty at first, and return error when it is empty.

2020-09-17 14:23 UTC, CHTJonas requested changes
Hi @hustclf, thanks for this. Could you please rebase and move the error checking/returning into the `Resolve()` function? Thanks!

2020-09-17 14:58 UTC, hustclf commented
@CHTJonas  please check it again.

2020-09-18 00:00 UTC, CHTJonas requested changes
Thanks - one tiny pedantic thing but otherwise this seems good!

2020-09-18 09:38 UTC, CHTJonas approved these changes

2020-09-18 09:48 UTC, SuperQ approved these changes
LGTM

2020-09-18 12:04 UTC, merged